Coin.Web/Areas/Security/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Coin.Web.Areas.Security.Controllers
{
    public class AccessController : Controller
    {
        // GET: Security/Access
        public ActionResult Login()
        {
            return View();
        }
    }
}

Coin.Web/Areas/Security/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Coin.Web.Areas.Security.Controllers
{
    public class RegistrationController : Controller
    {
        public ActionResult Register()
        {
            return View();
        }
    }
}

Coin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Coin.Web/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coin</title>

    <meta name="keywords" content="Coin,Bit,BitCoin" />
    <meta name="description" content="" />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <!-- WEB FONTS : use %7C instead of | (pipe) -->
    @*<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />*@

    <!-- CORE CSS -->
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- REVOLUTION SLIDER -->
    <link href="~/assets/plugins/slider.revolution/css/extralayers.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/plugins/slider.revolution/css/settings.css" rel="stylesheet" type="text/css" />

    <!-- THEME CSS -->
    <link href="~/assets/css/essentials.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/layout.css" rel="stylesheet" type="text/css" />

    <!-- PAGE LEVEL SCRIPTS -->
    <link href="~/assets/css/header-1.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/color_scheme/green.css" rel="stylesheet" type="text/css" id="color_scheme" />
    <link href="~/assets/plugins/styleswitcher/styleswitcher.css" rel="stylesheet" type="text/css"/>

</head>
<body class="smoothscroll enable-animation">
    <!-- wrapper -->
    <div id="wrapper">

        <!-- Top Bar -->
        <div id="topBar">
            <div class="container">

                <!-- right -->
                <ul class="top-links list-inline pull-right">
                    <li class="text-welcome hidden-xs">Welcome to Smarty, <strong>John Doe</strong></li>
                    <li>
                        <a class="dropdown-toggle no-text-underline" href="@Url.Action("Login", "Access", new { area="Security" })">
                            <i class="fa fa-user hidden-xs"></i>Login
                        </a>

                    </li>
                </ul>

                <!-- left -->
                @*<ul class="top-links list-inline">
                        <li class="hidden-xs"><a href="page-contact-1.html">CONTACT</a></li>
                        <li>
                            <a class="dropdown-toggle no-text-underline" data-toggle="dropdown" href="#"><img class="flag-lang" src="~/assets/images/flags/us.png" width="16" height="11" alt="lang" /> ENGLISH</a>
                            <ul class="dropdown-langs dropdown-menu">
                                <li><a tabindex="-1" href="#"><img class="flag-lang" src="~/assets/images/flags/us.png" width="16" height="11" alt="lang" /> ENGLISH</a></li>
                                <li class="divider"></li>
                                <li><a tabindex="-1" href="#"><img class="flag-lang" src="~/assets/images/flags/de.png" width="16" height="11" alt="lang" /> GERMAN</a></li>
                                <li><a tabindex="-1" href="#"><img class="flag-lang" src="~/assets/images/flags/ru.png" width="16" height="11" alt="lang" /> RUSSIAN</a></li>
                                <li><a tabindex="-1" href="#"><img class="flag-lang" src="~/assets/images/flags/it.png" width="16" height="11" alt="lang" /> ITALIAN</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="dropdown-toggle no-text-underline" data-toggle="dropdown" href="#">USD</a>
                            <ul class="dropdown-langs dropdown-menu">
                                <li><a tabindex="-1" href="#">USD</a></li>
                                <li class="divider"></li>
                                <li><a tabindex="-1" href="#">EUR</a></li>
                                <li><a tabindex="-1" href="#">GBP</a></li>
                            </ul>
                        </li>
                    </ul>*@

            </div>
        </div>
        <!-- /Top Bar -->
        <!--Main menu-->
        <div id="header" class="sticky shadow-after-3 clearfix">

            <!-- TOP NAV -->
            <header id="topNav">
                <div class="container">

                    <!-- Mobile Menu Button -->
                    <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>                 
                    <!-- Logo -->
                    <a class="logo pull-left" href="index.html">
                        <img src="~/assets/images/logo_dark.png" alt="" />
                    </a>

                  
                    <div class="navbar-collapse pull-right nav-main-collapse collapse submenu-dark">
                        <nav class="nav-main">
                            <ul id="topMain" class="nav nav-pills nav-main">
                                <li>
                                    <a href="#">
                                        BUY/SELL BTC
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        SEND MONEY INTERNTIONALLY
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        BTC WALLET
                                    </a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Register", "Registration", new { area="Security" })">
                                        REGISTER
                                    </a>
                                </li>

                                <li>
                                    <a id="sidepanel_btn" href="#" class="fa fa-bars"></a>
                                </li>
                            </ul>

                        </nav>
                    </div>

                </div>
            </header>
            <!-- /Top Nav -->
        </div>
        <!-- Close Main Menu-->

        <div>
            <!--Body-->
            @RenderBody()
            <!-- FOOTER -->
            <footer id="footer">
                <div class="container">

                    <div class="row">

                        <div class="col-md-4">
                            <!-- Footer Logo -->
                            <img class="footer-logo" src="~/assets/images/logo-footer.png" alt="" />
                            <!-- Contact Address -->
                            <address>
                                <ul class="list-unstyled">
                                    <li class="footer-sprite address">
                                      20, Eleyele road  Ibadan, Nigeria<br>
                                    </li>
                                    <li class="footer-sprite phone">
                                        Phone: +234 7039401235
                                    </li>
                                    <li class="footer-sprite email">
                                        <a href="mailto:support@yourname.com">support@coin.com</a>
                                    </li>
                                </ul>
                            </address>
                            <!-- /Contact Address -->

                        </div>
                        <div class="col-md-4">

                            <!-- Links -->
                            <h4 class="letter-spacing-1">INTRODUCTION</h4>
                            <ul class="footer-links list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Escrowed Trade</a></li>
                                <li><a href="#">Press</a></li>
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Legal & Policy</a></li>
                                <li><a href="#">Become our partner</a></li>
                            </ul>
                            <!-- /Links -->

                        </div>

                        <div class="col-md-4">

                            <!-- Newsletter Form -->
                            <h4 class="letter-spacing-1">KEEP IN TOUCH</h4>
                            <!-- Social Icons -->
                            <div class="margin-top-20">
                                <a href="#" class="social-icon social-icon-border social-facebook pull-left" data-toggle="tooltip" data-placement="top" title="Facebook">

                                    <i class="icon-facebook"></i>
                                    <i class="icon-facebook"></i>
                                </a>

                                <a href="#" class="social-icon social-icon-border social-twitter pull-left" data-toggle="tooltip" data-placement="top" title="Twitter">
                                    <i class="icon-twitter"></i>
                                    <i class="icon-twitter"></i>
                                </a>

                                <a href="#" class="social-icon social-icon-border social-gplus pull-left" data-toggle="tooltip" data-placement="top" title="Google plus">
                                    <i class="icon-gplus"></i>
                                    <i class="icon-gplus"></i>
                                </a>

                                <a href="#" class="social-icon social-icon-border social-linkedin pull-left" data-toggle="tooltip" data-placement="top" title="Linkedin">
                                    <i class="icon-linkedin"></i>
                                    <i class="icon-linkedin"></i>
                                </a>

                                <a href="#" class="social-icon social-icon-border social-rss pull-left" data-toggle="tooltip" data-placement="top" title="Rss">
                                    <i class="icon-rss"></i>
                                    <i class="icon-rss"></i>
                                </a>

                            </div>
                            <!-- /Social Icons -->

                        </div>

                    </div>

                </div>

                <div class="copyright">
                    <div class="container">
                        <ul class="pull-right nomargin list-inline mobile-block">
                            <li><a href="#">Terms &amp; Conditions</a></li>
                            <li>&bull;</li>
                            <li><a href="#">Privacy</a></li>
                        </ul>
                        &copy; All Rights Reserved, Company LTD
                    </div>
                </div>
            </footer>
            <!-- /FOOTER -->
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- JAVASCRIPT FILES -->
    <script type="text/javascript">var plugin_path = '../../assets/plugins/';</script>
    <script type="text/javascript" src="~/assets/plugins/jquery/jquery-2.1.4.min.js"></script>

    <script type="text/javascript" src="~/assets/js/scripts.js"></script>

    <!-- REVOLUTION SLIDER -->
    <script type="text/javascript" src="~/assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="~/assets/js/view/demo.revolution_slider.js"></script>
</body>
</html>